module.exports = {
  extends: "airbnb",
  parser: "babel-eslint",
  rules: {
    "array-bracket-spacing": 1,
    "arrow-body-style": 1,
    "arrow-parens": 1,
    "block-spacing": 1,
    "brace-style": 1,
    "comma-dangle": 1,
    "comma-spacing": 1,
    "consistent-return": 0,
    "eol-last": 1,
    eqeqeq: 1,
    "func-call-spacing": 1,
    "function-paren-newline": 1,
    "global-require": 1,
    "import/first": 1,
    "import/newline-after-import": 1,
    "import/no-cycle": 0,
    "import/no-duplicates": 1,
    "import/order": 1,
    "import/prefer-default-export": 0,
    indent: 1,
    "jsx-a11y/alt-text": 1,
    "jsx-a11y/anchor-is-valid": 0,
    "jsx-a11y/click-events-have-key-events": 1,
    "jsx-a11y/heading-had-content": 0,
    "jsx-a11y/href-no-hash": [0],
    "jsx-a11y/interactive-supports-focus": 1,
    "jsx-a11y/label-has-associated-control": 0,
    "jsx-a11y/label-has-for": 0,
    "jsx-a11y/mouse-events-have-key-events": 1,
    "jsx-a11y/no-noninteractive-element-interactions": 1,
    "jsx-a11y/no-noninteractive-element-to-interactive-role": 1,
    "jsx-a11y/no-noninteractive-tabindex": 1,
    "jsx-a11y/no-static-element-interactions": 1,
    "key-spacing": 1,
    "keyword-spacing": 1,
    "lines-between-class-members": 1,
    "max-len": [
      "warn",
      100,
      2,
      {
        ignoreComments: false,
        ignoreRegExpLiterals: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreUrls: true,
      }
    ],
    "newline-per-chained-call": 1,
    "no-console": 0,
    "no-extra-semi": 1,
    "no-floating-decimal": 1,
    "no-mixed-spaces-and-tabs": 0,
    "no-multi-spaces": 1,
    "no-nested-ternary": 1,
    "no-param-reassign": 0,
    "no-plusplus": 1,
    "no-restricted-syntax": 0,
    "no-sequences": 0,
    "no-spaced-func": 1,
    "no-tabs": 0,
    "no-trailing-spaces": 1,
    "no-underscore-dangle": 0,
    "no-unexpected-multiline": 1,
    "no-unneeded-ternary": 1,
    "no-unused-vars": 1,
    "no-useless-constructor": 1,
    "object-curly-newline": 1,
    "object-curly-spacing": 1,
    "object-property-newline": 1,
    "object-shorthand": 1,
    "operator-linebreak": 1,
    "padded-blocks": 1,
    "prefer-const": 1,
    "prefer-destructuring": 1,
    quotes: 1,
    radix: 1,
    "react/button-has-type": 1,
    "react/default-props-match-prop-types": 1,
    "react/destructuring-assignment": 0,
    "react/forbid-prop-types": 1,
    "react/jsx-boolean-value": 1,
    "react/jsx-closing-bracket-location": 1,
    "react/jsx-closing-tag-location": 1,
    "react/jsx-curly-spacing": 1,
    "react/jsx-filename-extension": 0,
    "react/jsx-first-prop-new-line": 1,
    "react/jsx-indent-props": 1,
    "react/jsx-indent": 1,
    "react/jsx-max-props-per-line": 1,
    "react/jsx-no-bind": 1,
    "react/jsx-one-expression-per-line": 0,
    "react/jsx-props-no-multi-spaces": 1,
    "react/jsx-tag-spacing": 1,
    "react/jsx-wrap-multilines": 1,
    "react/no-array-index-key": 1,
    "react/no-did-update-set-state": 1,
    "react/no-unused-prop-types": 1,
    "react/no-unused-state": 1,
    "react/prefer-stateless-function": 0,
    "react/prop-types": [
      "warn",
      {
        ignore: [],
        customValidators: [],
        skipUndeclared: false,
      }
    ],
    "react/require-default-props": 1,
    "react/self-closing-comp": 1,
    "react/sort-comp": 1,
    semi: 1,
    "semi-spacing": 1,
    "semi-style": 1,
    "space-before-blocks": 1,
    "space-in-parens": 1,
    "space-infix-ops": 1,
    "spaced-comment": 1,
  },
  globals: {
    __APOLLO_STATE__: true,
    __CLIENT__: true,
    __DEVELOPMENT__: true,
    __DEVTOOLS__: true,
    __DISABLE_SSR__: true,
    __SERVER__: true,
    $: true,
    alert: true,
    describe: true,
    document: true,
    FileReader: true,
    it: true,
    module: true,
    socket: true,
    webpackIsomorphicTools: true,
    window: true,
  },
};
